rootProject.name = "interview"
include("thread-local")
include("lazy-init")
include("questions")
include("anonymous-class")
include("generics")
include("prototype")
include("command")
include("observer")
include("chain-of-responsibility")
include("threads")
include("state")
include("race-condition")
include("finite-state-machine")
include("one-more-chain-of-responsibility")
include("queue")
